# Generated by Django 5.1.7 on 2026-04-27 02:06

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('PARTICIPANT', 'Participant'), ('MEMBER', 'Member'), ('VOLUNTEER', 'Volunteer'), ('DGROUP_LEADER', 'DGroup Leader')], default=['PARTICIPANT'], max_length=120),
        ),
    ]
