# Generated by Django 5.1.7 on 2026-04-27 02:10

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PARTICIPANT', 'Participant'), ('MEMBER', 'Member'), ('VOLUNTEER', 'Volunteer'), ('DGROUP_LEADER', 'DGroup Leader')], default='PARTICIPANT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ADMIN', 'Admin'), ('PARTICIPANT', 'Participant'), ('MEMBER', 'Member'), ('VOLUNTEER', 'Volunteer'), ('DGROUP_LEADER', 'DGroup Leader')], default=['PARTICIPANT'], max_length=120),
        ),
    ]
