# Generated by Django 5.1.7 on 2026-04-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role_alter_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_media',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
