# Generated by Django 5.1.7 on 2026-04-27

from django.db import migrations, models


def seed_and_migrate_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Role = apps.get_model("accounts", "Role")

    seed = [
        ("ADMIN", "Admin", True),
        ("PARTICIPANT", "Participant", True),
        ("MEMBER", "Member", True),
        ("VOLUNTEER", "Volunteer", True),
        ("DGROUP_LEADER", "DGroup Leader", True),
    ]
    role_index = {}
    for code, name, active in seed:
        r, _ = Role.objects.get_or_create(
            code=code,
            defaults={"name": name, "is_active": active, "description": ""},
        )
        role_index[code] = r

    def get_role(code: str):
        r = role_index.get(code)
        if r is None:
            r, _ = Role.objects.get_or_create(
                code=code,
                defaults={"name": code.replace("_", " ").title(), "is_active": True},
            )
            role_index[code] = r
        return r

    for user in User.objects.all().iterator():
        codes: set[str] = set()
        if getattr(user, "role", None):
            codes.add(str(user.role))
        packed = getattr(user, "roles", None)
        if packed:
            if isinstance(packed, (list, tuple)):
                for part in packed:
                    if part:
                        codes.add(str(part))
            else:
                for part in str(packed).split(","):
                    part = part.strip()
                    if part:
                        codes.add(part)
        if not codes:
            codes.add("PARTICIPANT")
        user.m2m_roles.set([get_role(code) for code in sorted(codes)])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_social_media"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="m2m_roles",
            field=models.ManyToManyField(
                blank=True,
                db_table="accounts_user_role_memberships",
                related_name="users",
                to="accounts.role",
            ),
        ),
        migrations.RunPython(seed_and_migrate_roles, noop_reverse),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="roles",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="m2m_roles",
            new_name="roles",
        ),
    ]
